# Generated by Django 5.2.10 on 2026-02-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_wallet_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='هل الحساب مفعل؟'),
        ),
    ]
