# Generated by Django 5.2.10 on 2026-02-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification_notificationread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='تفعيل الحساب'),
        ),
    ]
