# Generated by Django 5.2.10 on 2026-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activeuserscounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forced_withdrawal',
            field=models.BooleanField(default=True, help_text='سحب اجباري'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('canceled', 'ملغى من قبل المستخدم')], default='pending', max_length=10),
        ),
    ]
