# Generated by Django 5.2.10 on 2026-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_forced_withdrawal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disable_ordering_unitl_withdrawal',
            field=models.BooleanField(default=False, help_text='تعطيل الطلب حتى السحب'),
        ),
    ]
