# Generated by Django 5.2.10 on 2026-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_disable_ordering_unitl_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_withdrawn',
            field=models.BooleanField(default=False, help_text='هل سحب المستخدم؟'),
        ),
    ]
