# Generated by Django 5.2.10 on 2026-02-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_deposit_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'ط¸â€ڑط¸ظ¹ط·آ¯ ط·آ§ط¸â€\u200dط·آ§ط¸â€\xa0ط·ع¾ط·آ¸ط·آ§ط·آ±'), ('confirmed', 'ط·ع¾ط¸â€¦ ط·آ§ط¸â€\u200dط·ع¾ط·آ£ط¸ئ’ط¸ظ¹ط·آ¯'), ('rejected', 'ط¸â€¦ط·آ±ط¸ظ¾ط¸ث†ط·آ¶')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'ط¸â€¦ط·آ¹ط¸â€\u200dط¸â€ڑ'), ('approved', 'ط¸â€¦ط¸ث†ط·آ§ط¸ظ¾ط¸â€ڑ'), ('rejected', 'ط¸â€¦ط·آ±ط¸ظ¾ط¸ث†ط·آ¶'), ('canceled', 'ط¸â€¦ط¸â€\u200dط·ط›ط¸â€° ط¸â€¦ط¸â€\xa0 ط¸â€ڑط·آ¨ط¸â€\u200d ط·آ§ط¸â€\u200dط¸â€¦ط·آ³ط·ع¾ط·آ®ط·آ¯ط¸â€¦')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'ط·آ³ط·آ\xadط·آ¨/ط·ع¾ط·آ\xadط¸ث†ط¸ظ¹ط¸â€\u200d ط·آ®ط·آ§ط·آ±ط·آ¬ط¸ظ¹ (USDT)'), ('transfer', 'ط·ع¾ط·آ\xadط¸ث†ط¸ظ¹ط¸â€\u200d ط·آ¯ط·آ§ط·آ®ط¸â€\u200dط¸ظ¹')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disable_ordering_unitl_withdrawal',
            field=models.BooleanField(default=False, help_text='ط·ع¾ط·آ¹ط·آ·ط¸ظ¹ط¸â€\u200d ط·آ§ط¸â€\u200dط·آ·ط¸â€\u200dط·آ¨ ط·آ\xadط·ع¾ط¸â€° ط·آ§ط¸â€\u200dط·آ³ط·آ\xadط·آ¨'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='forced_withdrawal',
            field=models.BooleanField(default=True, help_text='ط·آ³ط·آ\xadط·آ¨ ط·آ§ط·آ¬ط·آ¨ط·آ§ط·آ±ط¸ظ¹'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='from_verified_source',
            field=models.BooleanField(default=False, help_text='ط¸â€،ط¸â€\u200d ط·آ§ط¸â€\u200dط¸â€¦ط·آ³ط·ع¾ط·آ®ط·آ¯ط¸â€¦ ط·آ¬ط·آ§ط·طŒ ط¸â€¦ط¸â€\xa0 ط¸â€¦ط·آµط·آ¯ط·آ± ط¸â€¦ط¸ث†ط·آ«ط¸ث†ط¸â€ڑط·ع؛'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_withdrawn',
            field=models.BooleanField(default=False, help_text='ط¸â€،ط¸â€\u200d ط·آ³ط·آ\xadط·آ¨ ط·آ§ط¸â€\u200dط¸â€¦ط·آ³ط·ع¾ط·آ®ط·آ¯ط¸â€¦ط·ع؛'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='ط·ع¾ط¸ظ¾ط·آ¹ط¸ظ¹ط¸â€\u200d ط·آ§ط¸â€\u200dط·آ\xadط·آ³ط·آ§ط·آ¨'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='ط¸â€،ط¸â€\u200d ط·آ§ط¸â€\u200dط¸â€¦ط·آ³ط·ع¾ط·آ®ط·آ¯ط¸â€¦ ط¸â€¦ط¸ث†ط·آ«ط¸ث†ط¸â€ڑ ط·آ¨ط¸â€،ط·ع؛'),
        ),
    ]
