# Generated by Django 5.2.10 on 2026-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_signup_ip_and_last_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled by user')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'Withdrawal to external wallet (USDT)'), ('transfer', 'Internal transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disable_ordering_unitl_withdrawal',
            field=models.BooleanField(default=False, help_text='Disable product ordering until the first withdrawal is completed.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='forced_withdrawal',
            field=models.BooleanField(default=True, help_text='Require withdrawal before allowing additional actions.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='from_verified_source',
            field=models.BooleanField(default=False, help_text='Whether the user came from a trusted referral source.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_withdrawn',
            field=models.BooleanField(default=False, help_text='Whether the user has already withdrawn at least once.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Whether the account is enabled.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this user is marked as verified.'),
        ),
    ]
