# Generated by Django 5.2.10 on 2026-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_deposit_status_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
