# Generated by Django 5.2.10 on 2026-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_last_wallet_address_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='freezen',
            field=models.BooleanField(default=False, help_text='تجميد الحساب وايقاف عمليات الطلب', verbose_name='تجميد الحساب'),
        ),
    ]
