# Generated by Django 5.2.10 on 2026-02-21 03:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_alter_deposit_status_alter_transaction_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('tron', 'TRON (TRC20)'), ('bep20', 'BNB Chain (BEP20)')], max_length=12, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('private_key', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('network',),
            },
        ),
        migrations.CreateModel(
            name='Relayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('tron', 'TRON (TRC20)'), ('bep20', 'BNB Chain (BEP20)')], max_length=12, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('private_key', models.TextField(blank=True)),
                ('min_native_balance', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=20)),
                ('topup_amount', models.DecimalField(decimal_places=8, default=Decimal('3'), max_digits=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('network',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('tron', 'TRON (TRC20)'), ('bep20', 'BNB Chain (BEP20)')], max_length=12)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('private_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='accounts.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('tron', 'TRON (TRC20)'), ('bep20', 'BNB Chain (BEP20)')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('destination_address', models.CharField(max_length=255)),
                ('txid', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('fee_payer', models.CharField(choices=[('relayer', 'Relayer'), ('user', 'User')], default='relayer', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweeps', to='wallet.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('tron', 'TRON (TRC20)'), ('bep20', 'BNB Chain (BEP20)')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('txid', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallet.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['network', 'address'], name='wallet_wall_network_f22286_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'network'], name='wallet_wall_user_id_6b0c22_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'network'), name='uniq_wallet_user_network'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('profile', 'network'), name='uniq_wallet_profile_network'),
        ),
        migrations.AddIndex(
            model_name='sweep',
            index=models.Index(fields=['wallet', 'status'], name='wallet_swee_wallet__b87dff_idx'),
        ),
        migrations.AddIndex(
            model_name='sweep',
            index=models.Index(fields=['network', 'created_at'], name='wallet_swee_network_457c28_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['network', 'status'], name='wallet_depo_network_a3af19_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_depo_wallet__7de6c7_idx'),
        ),
    ]
