# Generated by Django 5.2.10 on 2026-02-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayer',
            name='rpc_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
