# Generated by Django 5.2.10 on 2026-02-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_relayer_rpc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayer',
            name='bscscan_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
