# Generated by Django 5.2.10 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_relayer_bscscan_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayer",
            name="trongrid_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
