# Generated by Django 5.2.10 on 2026-02-23 06:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_relayer_trongrid_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayer',
            name='reserve_native_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.01'), max_digits=20),
        ),
    ]
