# Generated by Django 5.2.10 on 2026-02-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_relayer_reserve_native_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_scanned_block',
            field=models.BigIntegerField(default=0),
        ),
    ]
