# Generated by Django 5.2.10 on 2026-02-23 14:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_wallet_last_scanned_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletServiceSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bep20_rpc_url", models.CharField(blank=True, max_length=500)),
                ("fallback_bep20_rpc_url", models.CharField(blank=True, max_length=500)),
                ("bep20_rpc_fallback_urls", models.TextField(blank=True)),
                ("bep20_autocheck_lookback_blocks", models.PositiveIntegerField(default=1000)),
                ("bep20_initial_lookback_blocks", models.PositiveIntegerField(default=10000)),
                ("bep20_autocheck_chunk_size", models.PositiveIntegerField(default=200)),
                (
                    "bep20_relayer_reserve_bnb",
                    models.DecimalField(decimal_places=8, default=Decimal("0.01"), max_digits=20),
                ),
                ("bscscan_api_url", models.CharField(default="https://api.etherscan.io/v2/api", max_length=500)),
                ("bscscan_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "bep20_deposit_source",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (RPC preferred)"),
                            ("rpc", "RPC only"),
                            ("bscscan", "BscScan only"),
                        ],
                        default="rpc",
                        max_length=20,
                    ),
                ),
                ("bep20_bscscan_offset", models.PositiveIntegerField(default=200)),
                ("bep20_bscscan_max_pages", models.PositiveIntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wallet Service Setting",
                "verbose_name_plural": "Wallet Service Settings",
            },
        ),
    ]
