# Generated by Django 5.2.10 on 2026-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_walletservicesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletservicesetting",
            name="bep20_explorer_chain_id",
            field=models.PositiveIntegerField(default=56),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="bep20_rpc_timeout_seconds",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="bep20_sweep_receipt_timeout_seconds",
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="bep20_topup_receipt_timeout_seconds",
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="bep20_usdt_contract",
            field=models.CharField(default="55d398326f99059fF775485246999027B3197955", max_length=255),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="bep20_usdt_decimals",
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="bscscan_v2_api_url",
            field=models.CharField(default="https://api.etherscan.io/v2/api", max_length=500),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="explorer_timeout_seconds",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="tron_api_timeout_seconds",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="tron_endpoint_uri",
            field=models.CharField(default="https://api.trongrid.io", max_length=500),
        ),
        migrations.AddField(
            model_name="walletservicesetting",
            name="tron_usdt_contract",
            field=models.CharField(default="TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t", max_length=255),
        ),
    ]
