# Generated by Django 5.2.10 on 2026-02-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_walletservicesetting_more_runtime_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletservicesetting",
            name="tron_usdt_decimals",
            field=models.PositiveIntegerField(default=6),
        ),
    ]
