# Generated by Django 5.2.10 on 2026-02-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
