# Generated by Django 5.2.10 on 2026-02-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='profit',
        ),
    ]
