# Generated by Django 5.2.10 on 2026-02-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='platform',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.platformmodel'),
        ),
    ]
