# Generated by Django 5.2.10 on 2026-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_userprogress_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmodel',
            name='show_only_from_not_verified_source',
            field=models.BooleanField(default=False, help_text='اعرض فقط للاشخاص من مصدر غير موثوق؟'),
        ),
    ]
