# Generated by Django 5.2.10 on 2026-02-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_platformmodel_show_only_from_not_verified_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroupItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productgroupmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='products.productmodel')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('group', 'product'), name='unique_product_per_group'),
                    models.CheckConstraint(condition=models.Q(quantity__gte=1), name='group_item_quantity_gte_1'),
                ],
            },
        ),
        migrations.AddField(
            model_name='productgroupmodel',
            name='products',
            field=models.ManyToManyField(related_name='groups', through='products.ProductGroupItemModel', to='products.productmodel'),
        ),
    ]
