# Generated by Django 5.2.10 on 2026-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_group_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroupmodel',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='stage',
        ),
        migrations.AddField(
            model_name='productgroupmodel',
            name='stage',
            field=models.IntegerField(null=True),
        ),
    ]
