# Generated by Django 5.2.10 on 2026-02-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_productgroupmodel_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgroupmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_groups",
                to="products.categorymodel",
            ),
        ),
    ]
