# Generated by Django 5.2.10 on 2026-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productgroupmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgroupmodel",
            name="products_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="productgroupmodel",
            name="target_total_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name="ProductGroupItemModel",
        ),
    ]
