# Generated by Django 5.2.10 on 2026-02-19 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productgroupitem_add_target_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='product',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='products.productgroupmodel'),
        ),
    ]
