# Generated by Django 5.2.10 on 2026-02-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_userprogress_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='profit',
        ),
        migrations.AddField(
            model_name='productgroupmodel',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
