# Generated by Django 5.2.10 on 2026-02-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productmodel_profit_productgroupmodel_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
    ]
