# Generated by Django 5.2.10 on 2026-02-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productgroupsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmodel',
            name='close_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformmodel',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='اغلاق مع رسالة'),
        ),
    ]
