# Generated by Django 5.2.10 on 2026-02-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_platformmodel_close_msg_platformmodel_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformmodel',
            name='close_msg',
        ),
        migrations.RemoveField(
            model_name='platformmodel',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='platformmodel',
            name='msg',
            field=models.TextField(blank=True, null=True, verbose_name='رسالة'),
        ),
    ]
