# Generated by Django 5.2.10 on 2026-02-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_platformmodel_close_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
