# Generated by Django 5.2.10 on 2026-02-27 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_platformmodel_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="platformmodel",
            name="visible_to_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, this platform is visible to all matching users.",
                related_name="platform_visibility",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
