# Generated by Django 5.2.10 on 2026-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_platformmodel_visible_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmodel',
            name='show_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
