# Generated by Django 5.2.10 on 2026-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_platformmodel_show_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmodel',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='ترتيب العرض. المنصات ذات الرقم الأقل تظهر أولاً.'),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='show_to_all',
            field=models.BooleanField(default=False, help_text='اذا تم تفعيل هذا الخيار، سيتم عرض المنصة لجميع المستخدمين بغض النظر عن الاعدادات الاخرى.', verbose_name='اعرض للجميع'),
        ),
    ]
